media: 
  input: assets/uploads
  output: assets/img

content:
  - name: courses
    label: Courses
    path: src/content/courses
    type: collection
    fields: 
      - name: title
        label: Title
        type: string
